services:
  #mongo db services 
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
  #node js services
  api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
      - /app/node_modules
    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongo_db:27017/nodejs-case
      JWT_SECRET: 2003Rumeysa
      CHOKIDAR_USEPOLLING: "true"
      NODE_ENV: development

    command: npm run dev

    depends_on:
      - mongo_db  
volumes:
  mongo_db: {}      
    

 

